"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const { syncCargoLockVersions, WORKSPACE_MEMBERS } = require("./cargo-lock-version");

/** A Cargo.lock shaped like the real one: several blocks, cargo's key order. */
function lock(teamcluVersion, amuxdVersion) {
  return [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    "[[package]]",
    'name = "aes-gcm"',
    'version = "0.10.3"',
    "",
    "[[package]]",
    'name = "amuxd"',
    `version = "${amuxdVersion}"`,
    "dependencies = [",
    ' "aes-gcm",',
    "]",
    "",
    "[[package]]",
    'name = "teamclu"',
    `version = "${teamcluVersion}"`,
    "dependencies = [",
    ' "amuxd",',
    "]",
    "",
  ].join("\n");
}

test("rewrites both workspace members and reports what changed", () => {
  const out = syncCargoLockVersions(lock("0.3.1-beta.7", "0.3.1-beta.7"), "0.3.1-beta.8");
  assert.deepEqual(out.changed.sort(), ["amuxd", "teamclu"]);
  assert.deepEqual(out.missing, []);
  assert.match(out.text, /name = "teamclu"\nversion = "0\.3\.1-beta\.8"/);
  assert.match(out.text, /name = "amuxd"\nversion = "0\.3\.1-beta\.8"/);
});

test("leaves unrelated packages alone", () => {
  const out = syncCargoLockVersions(lock("0.3.1-beta.7", "0.3.1-beta.7"), "0.3.1-beta.8");
  assert.match(out.text, /name = "aes-gcm"\nversion = "0\.10\.3"/);
});

test("already in sync is a no-op with nothing reported as changed", () => {
  const before = lock("0.3.1-beta.8", "0.3.1-beta.8");
  const out = syncCargoLockVersions(before, "0.3.1-beta.8");
  assert.equal(out.text, before);
  assert.deepEqual(out.changed, []);
});

test("a half-synced lockfile still gets fixed", () => {
  // What the bug actually produced: one crate bumped by a stray local build,
  // the other left behind.
  const out = syncCargoLockVersions(lock("0.3.1-beta.8", "0.3.1-beta.7"), "0.3.1-beta.8");
  assert.deepEqual(out.changed, ["amuxd"]);
  assert.match(out.text, /name = "amuxd"\nversion = "0\.3\.1-beta\.8"/);
});

test("a missing package is reported, not silently skipped", () => {
  const out = syncCargoLockVersions('[[package]]\nname = "other"\nversion = "1.0.0"\n', "9.9.9");
  assert.deepEqual(out.missing.sort(), ["amuxd", "teamclu"]);
  assert.deepEqual(out.changed, []);
});

test("a dependency merely naming a member is not rewritten", () => {
  // `dependencies = [" amuxd"]` entries carry the name without a version line;
  // the block anchor must not reach them.
  const text = ['[[package]]', 'name = "teamclu"', 'version = "1.0.0"', 'dependencies = [', ' "amuxd",', ']', ''].join("\n");
  const out = syncCargoLockVersions(text, "2.0.0", ["amuxd"]);
  assert.deepEqual(out.missing, ["amuxd"]);
  assert.equal(out.text, text);
});

test("a CRLF lockfile is rewritten and keeps its line endings", () => {
  // The Windows release runner checks out with core.autocrlf=true. An \n-only
  // pattern found nothing there, so the bump script aborted with "Cargo.lock has
  // no entry for: teamclu, amuxd" and took the whole nightly build down.
  const before = lock("0.3.1-beta.8", "0.3.1-beta.8").replace(/\n/g, "\r\n");
  const out = syncCargoLockVersions(before, "0.3.1-beta.9");
  assert.deepEqual(out.missing, []);
  assert.deepEqual(out.changed.sort(), ["amuxd", "teamclu"]);
  assert.match(out.text, /name = "teamclu"\r\nversion = "0\.3\.1-beta\.9"/);
  assert.match(out.text, /name = "amuxd"\r\nversion = "0\.3\.1-beta\.9"/);
  assert.ok(!/[^\r]\n/.test(out.text), "must not introduce bare LF into a CRLF file");
});

test("the member list is the two crates the bump script rewrites", () => {
  assert.deepEqual([...WORKSPACE_MEMBERS].sort(), ["amuxd", "teamclu"]);
});
